Articacts release

diff --git a/.github/workflows/adreno_nightly_wheel.yml b/.github/workflows/adreno_nightly_wheel.yml
--- a/.github/workflows/adreno_nightly_wheel.yml
+++ b/.github/workflows/adreno_nightly_wheel.yml
@@ -57,7 +57,6 @@ jobs:
                conda run -n py38 ./ci/task/build_wheel.sh
            mkdir -p nightly
            cp wheels/*.whl nightly/
-           mv wheels/*.whl ${BUILD_WHEEL_PATH}/
            bash ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cpu \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -83,7 +82,6 @@ jobs:
                conda run -n py38 ./ci/task/build_wheel.sh
            mkdir -p nightly
            cp wheels/*.whl nightly/
-           mv wheels/*.whl ${BUILD_WHEEL_PATH}/
            bash ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cuda-12.1 \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -110,7 +108,6 @@ jobs:
                conda run -n py38 ./ci/adreno/build_wheel.sh
            mkdir -p ../../nightly
            cp wheels/*.whl ../../nightly/
-           mv wheels/*.whl ${BUILD_WHEEL_PATH}/
            bash ../../ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cpu \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -138,11 +135,6 @@ jobs:
                conda run -n py38 ./ci/adreno/build_wheel.sh
            mkdir -p ../../nightly
            cp wheels/*.whl ../../nightly/
-           gh release delete mlc-nightly-linux --cleanup-tag --yes --repo "$RELEASE_REPO" || true
-           gh release create mlc-nightly-linux --latest --title mlc-nightly-linux --repo "$RELEASE_REPO" --notes "Linux MLC Nightly builds"
-           gh release upload mlc-nightly-linux ../../nightly/*.whl --clobber --repo "$RELEASE_REPO"
-           rm -rf ../../nightly/
-           mv wheels/*.whl ${BUILD_WHEEL_PATH}/
            bash ../../ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cuda-12.1 \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -150,20 +142,33 @@ jobs:
                -e ADRENOACCL_SDK /adrenoaccl_sdk \
                conda run -n py38 ./ci/adreno/build_clean.sh
            cd -
-           git tag -f -a mlc-nightly-linux -m "Update nightly commit id"
-           git push origin -f --tags
       - name: Build LLM Models
         shell: bash -l {0}
         run: |
+           conda remove -y --name mlc-ci --all
+           conda create -y -n mlc-ci -c conda-forge \
+               llvmdev=15 cmake>=3.24 git rust numpy \
+               decorator psutil typing_extensions scipy \
+               attrs git-lfs gcc=10.4 gxx=10.4 python=3.8
+           conda activate mlc-ci
+           conda env list
+           pip install nightly/mlc_llm_adreno_cuda*.whl
+           pip install nightly/tvm_adreno_mlc_cuda*.whl
+           export LD_LIBRARY_PATH=$CUDA_PATH/lib64/
+           export PATH=$CUDA_PATH/bin:$PATH
+           python -c "import mlc_llm; print(mlc_llm.__path__)"
+           python -c "import tvm; print(tvm.__path__)"
            sh ci/task/build_adreno_models.sh $LLM_MODEL_REPO $LLM_ARTIFACTS
       - name: Publish Artifacts
         shell: bash -l {0}
         run: |
+           gh release delete mlc-nightly --cleanup-tag --yes --repo "$RELEASE_REPO" || true
+           gh release create mlc-nightly --latest --title mlc-nightly --repo "$RELEASE_REPO" --notes "MLC Nightly builds"
+           gh release upload mlc-nightly ../../nightly/*.whl --clobber --repo "$RELEASE_REPO"
+           rm -rf ../../nightly/
            gh release delete llm-nightly-artifacts --cleanup-tag --yes --repo "$RELEASE_REPO" || true
            gh release create llm-nightly-artifacts --latest --title llm-nightly-artifacts --repo "$RELEASE_REPO" --notes "Android (Adreno) LLM Nightly artifacts"
            gh release upload llm-nightly-artifacts $LLM_ARTIFACTS/dist/libs/*.so --clobber --repo "$RELEASE_REPO"
-           git tag -f -a llm-nightly-artifacts -m "Update nightly commit id"
-           git push origin -f --tags
 
   BuildPackageWindows:
     needs: [BuildPackageLinux]
@@ -228,9 +233,9 @@ jobs:
            cd 3rdparty/tvm/python
            python.exe .\setup.py bdist_wheel --plat-name win_amd64
            Pop-Location
-           try { gh release delete mlc-nightly-windows --cleanup-tag --yes --repo $Env:RELEASE_REPO } catch { }
-           gh release create mlc-nightly-windows --latest --title mlc-nightly-windows --repo $Env:RELEASE_REPO --notes "Windows MLC nightly builds"
-           foreach ($i in Get-ChildItem -Path python/dist) {gh release upload mlc-nightly-windows .\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
-           foreach ($i in Get-ChildItem -Path 3rdparty/tvm/python/dist) {gh release upload mlc-nightly-windows .\3rdparty\tvm\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
+           #try { gh release delete mlc-nightly --cleanup-tag --yes --repo $Env:RELEASE_REPO } catch { }
+           #gh release create mlc-nightly --latest --title mlc-nightly --repo $Env:RELEASE_REPO --notes "Windows MLC nightly builds"
+           foreach ($i in Get-ChildItem -Path python/dist) {gh release upload mlc-nightly .\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
+           foreach ($i in Get-ChildItem -Path 3rdparty/tvm/python/dist) {gh release upload mlc-nightly .\3rdparty\tvm\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
         env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
