MLC Staging pipeline (#21)
Co-authored-by: Siva <quic_sivb@quicinc.com>

diff --git a/.github/workflows/adreno_rebase_staging_release_gen.yml b/.github/workflows/adreno_rebase_staging_release_gen.yml
--- a/.github/workflows/adreno_rebase_staging_release_gen.yml
+++ b/.github/workflows/adreno_rebase_staging_release_gen.yml
@@ -15,21 +15,178 @@
 # specific language governing permissions and limitations
 # under the License.
 
-# Checkout mainline commit on local repo and run tests.
-name: Adreno Package Generation
+# GH actions.
+
+name: Adreno MLC Rebase Staging Release
 
 on:
-  schedule:
-    # 2:30 AM IST
-    - cron: "1 20 * * *"
   workflow_dispatch:
 
 concurrency:
-  group: mlcpkg
+  group: CI-${{ github.event.pull_request.number || github.sha }}
   cancel-in-progress: true
 
 jobs:
+  MLC-Build-Linux:
+    if: ${{ github.repository == 'gpgpu/mlc-llm' }}
+    runs-on: mlc-linux-ci
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          # submodules: 'recursive'
+          ref: 'rebase-main'
+          fetch-depth: 0
+      - name: Sync Sub modules
+        shell: bash -l {0}
+        run: |
+          git submodule sync --recursive
+          git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          cd 3rdparty/tvm
+          git checkout -b rebase_staging origin/rebase_staging
+          git submodule sync --recursive
+          git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          cd -
+      - name: Lint
+        shell: bash -l {0}
+        run: |
+           set -e
+           bash ci/bash.sh mlcaidev/ci-cpu \
+               -e GPU cpu \
+               -e MLC_CI_SETUP_DEPS 1 -j 1 \
+               bash --login /docker/with_the_same_user \
+               "conda run -n ci-lint ci/task/isort.sh"
+           bash ci/bash.sh mlcaidev/ci-cpu \
+               -e GPU cpu \
+               -e MLC_CI_SETUP_DEPS 1 -j 1 \
+               bash --login /docker/with_the_same_user \
+               "conda run -n ci-lint ci/task/black.sh"
+           bash ci/bash.sh mlcaidev/ci-cpu \
+               -e GPU cpu \
+               -e MLC_CI_SETUP_DEPS 1 -j 1 \
+               bash --login /docker/with_the_same_user \
+               "conda run -n ci-lint ci/task/mypy.sh"
+           bash ci/bash.sh mlcaidev/ci-cpu \
+               -e GPU cpu \
+               -e MLC_CI_SETUP_DEPS 1 -j 1 \
+               bash --login /docker/with_the_same_user \
+               "conda run -n ci-lint ci/task/pylint.sh"
+           bash ci/bash.sh mlcaidev/ci-cpu \
+               -e GPU cpu \
+               -e MLC_CI_SETUP_DEPS 1 -j 1 \
+               bash --login /docker/with_the_same_user \
+               "conda run -n ci-lint ci/task/clang-format.sh"
+      - name: Compile MLC
+        shell: bash -l {0}
+        run: |
+           mkdir -p build && cd build
+           echo set\(TVM_HOME 3rdparty/tvm\) >> config.cmake
+           echo set\(CMAKE_BUILD_TYPE RelWithDebInfo\) >> config.cmake
+           echo set\(USE_CUDA ON\) >> config.cmake
+           echo set\(USE_CUTLASS OFF\) >> config.cmake
+           echo set\(USE_CUBLAS OFF\) >> config.cmake
+           echo set\(USE_ROCM OFF\) >> config.cmake
+           echo set\(USE_VULKAN OFF\) >> config.cmake
+           echo set\(USE_METAL OFF\) >> config.cmake
+           echo set\(USE_OPENCL ON\) >> config.cmake
+           echo set\(USE_OPENCL_ENABLE_HOST_PTR ON\) >> config.cmake
+           echo set\(USE_FLASHINFER OFF\) >> config.cmake
+           echo set\(USE_ADRENO_ACCL "${ADRENOACCL_SDK}"\) >> config.cmake
+           cmake .. && cmake --build . --parallel $(nproc) && cd ..
+      - name: Compile TVM
+        shell: bash -l {0}
+        run: |
+           mkdir -p 3rdparty/tvm/build/;cd 3rdparty/tvm/build/;
+           cp ../cmake/config.cmake . -f;
+           echo set\(USE_OPENCL ON\) >> config.cmake;
+           echo set\(USE_LLVM ON\) >> config.cmake;
+           echo set\(USE_CUDA ON\) >> config.cmake;
+           echo set\(USE_ADRENO_ACCL "${ADRENOACCL_SDK}"\) >> config.cmake
+           cmake .. && cmake --build . --parallel $(nproc); cd -
+      - name: Check Build Status
+        shell: bash -l {0}
+        run: |
+           export PYTHONPATH=./python:$PYTHONPATH
+           export PYTHONPATH=$PWD/3rdparty/tvm/python:$PYTHONPATH
+           export PATH=$CUDA_PATH/bin:$PATH
+           python -c "import mlc_llm; print(mlc_llm.__path__)"
+      - name: Build LLM Models
+        shell: bash -l {0}
+        run: |
+           export PYTHONPATH=./python:$PYTHONPATH
+           export PYTHONPATH=$PWD/3rdparty/tvm/python:$PYTHONPATH
+           export PATH=$CUDA_PATH/bin:$PATH
+           python -c "import mlc_llm; print(mlc_llm.__path__)"
+           sh ci/task/build_adreno_models.sh $CI_LLM_INVENTORY
+  MLC-Build-Windows:
+    needs: [MLC-Build-Linux]
+    if: ${{ github.repository == 'gpgpu/mlc-llm' }}
+    runs-on: mlc-windows
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          #submodules: 'recursive'
+          ref: ''
+      - name: Sync Sub modules
+        shell: powershell
+        run: |
+          git submodule sync --recursive
+          git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          Push-Location
+          cd 3rdparty/tvm
+          git checkout -b rebase_staging origin/rebase_staging
+          git submodule sync --recursive
+          git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          Pop-Location
+      - name: Compile MLC
+        shell: powershell
+        run: |
+           Push-Location
+           New-Item -ItemType Directory -Force -Path "./build"
+           cd build
+           echo $Env:PATH
+           Add-Content config.cmake "set(TVM_HOME 3rdparty/tvm)"
+           Add-Content config.cmake "set(CMAKE_BUILD_TYPE RelWithDebInfo)"
+           Add-Content config.cmake "set(USE_CUDA OFF)"
+           Add-Content config.cmake "set(USE_CUTLASS OFF)"
+           Add-Content config.cmake "set(USE_CUBLAS OFF)"
+           Add-Content config.cmake "set(USE_ROCM OFF)"
+           Add-Content config.cmake "set(USE_VULKAN OFF)"
+           Add-Content config.cmake "set(USE_METAL OFF)"
+           Add-Content config.cmake "set(USE_OPENCL ON)"
+           Add-Content config.cmake "set(USE_OPENCL_ENABLE_HOST_PTR ON)"
+           Add-Content config.cmake "set(USE_FLASHINFER OFF)"
+           Add-Content config.cmake "set(USE_ADRENO_ACCL $ENV:ADRENOACCL_SDK_X86)"
+           Add-Content config.cmake "set(USE_ADRENO_ACCL_GRAPH_EXECUTOR $ENV:ADRENOACCL_SDK_X86)"
+           cmake .. -G "Visual Studio 17 2022" -A x64
+           cmake --build . --config Release --parallel $env:NUMBER_OF_PROCESSORS
+           Pop-Location
+      - name: Compile TVM
+        shell: powershell
+        run: |
+           Push-Location
+           New-Item -ItemType Directory -Force -Path "./3rdparty/tvm/build"
+           cd 3rdparty/tvm/build/;
+           cp ../cmake/config.cmake .
+           Add-Content config.cmake "set(USE_OPENCL $ENV:OPENCL_SDK_ADRENO_X86)"
+           Add-Content config.cmake "set(USE_LLVM $ENV:LLVM_CONFIG)"
+           Add-Content config.cmake "set(USE_ADRENO_ACCL $ENV:ADRENOACCL_SDK_X86)"
+           Add-Content config.cmake "set(USE_ADRENO_ACCL_GRAPH_EXECUTOR $ENV:ADRENOACCL_SDK_X86)"
+           cmake .. -G "Visual Studio 17 2022" -A x64
+           cmake --build . --config Release --parallel $env:NUMBER_OF_PROCESSORS
+           Pop-Location
+      - name: Check Build Status
+        shell: powershell
+        run: |
+           $env:PYTHONPATH = "$pwd\3rdparty\tvm\python;python"
+           python -c "import mlc_llm; print(mlc_llm.__path__)"
+      - name: Build LLM Models
+        shell: powershell
+        run: |
+           $env:PYTHONPATH = "$pwd\3rdparty\tvm\python;python"
+           python -c "import mlc_llm; print(mlc_llm.__path__)"
+           ci/task/build_adreno_models_win.ps1 $Env:CI_LLM_INVENTORY
   BuildPackageLinux:
+    needs: [MLC-Build-Windows]
     if: github.repository == 'gpgpu/mlc-llm'
     runs-on: mlc-linux-ci
     steps:
@@ -42,11 +199,16 @@ jobs:
         run: |
           git submodule sync --recursive
           git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          cd 3rdparty/tvm
+          git checkout -b rebase_staging origin/rebase_staging
+          git submodule sync --recursive
+          git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          cd -
       - name: Build MLC CPU Host Wheel
         shell: bash -l {0}
         run: |
            set -e
-           gh release delete nightly --cleanup-tag --yes --repo git@github.qualcomm.com:gpgpu/mlc-llm.git || true
+           gh release delete staging --cleanup-tag --yes --repo git@github.qualcomm.com:gpgpu/mlc-llm.git || true
            bash ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cpu \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -60,8 +222,8 @@ jobs:
                -e ADRENOACCL_SDK /adrenoaccl_sdk \
                -e WHEEL_EXT_NAME "_adreno_cpu" \
                conda run -n py38 ./ci/task/build_wheel.sh
-           mkdir -p nightly
-           cp wheels/*.whl nightly/
+           mkdir -p staging
+           cp wheels/*.whl staging/
            bash ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cpu \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -85,8 +247,8 @@ jobs:
                -e ADRENOACCL_SDK /adrenoaccl_sdk \
                -e WHEEL_EXT_NAME "_adreno_cuda" \
                conda run -n py38 ./ci/task/build_wheel.sh
-           mkdir -p nightly
-           cp wheels/*.whl nightly/
+           mkdir -p staging
+           cp wheels/*.whl staging/
            bash ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cuda-12.1 \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -111,8 +273,8 @@ jobs:
                -e ADRENOACCL_SDK /adrenoaccl_sdk \
                -e WHEEL_EXT_NAME "_adreno_mlc_cpu" \
                conda run -n py38 ./ci/adreno/build_wheel.sh
-           mkdir -p ../../nightly
-           cp wheels/*.whl ../../nightly/
+           mkdir -p ../../staging
+           cp wheels/*.whl ../../staging/
            bash ../../ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cpu \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -138,8 +300,8 @@ jobs:
                -e ADRENOACCL_SDK /adrenoaccl_sdk \
                -e WHEEL_EXT_NAME "_adreno_mlc_cuda" \
                conda run -n py38 ./ci/adreno/build_wheel.sh
-           mkdir -p ../../nightly
-           cp wheels/*.whl ../../nightly/
+           mkdir -p ../../staging
+           cp wheels/*.whl ../../staging/
            bash ../../ci/bash.sh mlcaidev/package-cu121 \
                -e GPU cuda-12.1 \
                -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
@@ -180,7 +342,7 @@ jobs:
            rm -rf `find mlc_llm-utils-linux-arm64 -name "*.a"`
            cp ${ADRENOACCL_SDK}/lib/* mlc_llm-utils-linux-arm64/lib/ -rfa
            tar jcvfp mlc_llm-utils-linux-arm64.tar.bz2 mlc_llm-utils-linux-arm64
-           mv mlc_llm-utils-linux-arm64.tar.bz2 ../nightly
+           mv mlc_llm-utils-linux-arm64.tar.bz2 ../staging
            cd ..
       - name: Build LLM Models
         shell: bash -l {0}
@@ -192,26 +354,25 @@ jobs:
                attrs git-lfs gcc=10.4 gxx=10.4 python=3.8
            conda activate mlc-ci
            conda env list
-           pip install nightly/mlc_llm_adreno_cuda*.whl
-           pip install nightly/tvm_adreno_mlc_cuda*.whl
+           pip install staging/mlc_llm_adreno_cuda*.whl
+           pip install staging/tvm_adreno_mlc_cuda*.whl
            export LD_LIBRARY_PATH=$CUDA_PATH/lib64/
            export PATH=$CUDA_PATH/bin:$PATH
            python -c "import mlc_llm; print(mlc_llm.__path__)"
            python -c "import tvm; print(tvm.__path__)"
-           sh ci/task/build_adreno_models.sh $CI_LLM_INVENTORY $CI_LLM_NIGHTLY_ARTIFACTS
+           sh ci/task/build_adreno_models.sh $CI_LLM_INVENTORY $CI_LLM_STAGING_ARTIFACTS
       - name: Publish Artifacts
         shell: bash -l {0}
         run: |
-           gh release delete mlc-nightly --cleanup-tag --yes --repo "$RELEASE_REPO" || true
-           gh release create mlc-nightly --latest --title mlc-nightly --repo "$RELEASE_REPO" --notes "MLC Nightly builds"
-           gh release upload mlc-nightly nightly/*.whl --clobber --repo "$RELEASE_REPO"
-           gh release upload mlc-nightly nightly/*.tar.bz2 --clobber --repo "$RELEASE_REPO"
-           cp nightly/* ${CI_PACKAGE_REPO_NIGHTLY}/ -rfa
-           rm -rf nightly
-           gh release delete llm-nightly-artifacts --cleanup-tag --yes --repo "$RELEASE_REPO" || true
-           gh release create llm-nightly-artifacts --latest --title llm-nightly-artifacts --repo "$RELEASE_REPO" --notes "Android (Adreno) LLM Nightly artifacts"
-           gh release upload llm-nightly-artifacts $LLM_ARTIFACTS/dist/libs/*.so --clobber --repo "$RELEASE_REPO"
-
+           gh release delete mlc-staging --cleanup-tag --yes --repo "$STAGING_RELEASE_REPO_MLC" || true
+           gh release create mlc-staging --latest --title mlc-staging --repo "$STAGING_RELEASE_REPO_MLC" --notes "MLC Nightly builds"
+           gh release upload mlc-staging staging/*.whl --clobber --repo "$STAGING_RELEASE_REPO_MLC"
+           gh release upload mlc-staging staging/*.tar.bz2 --clobber --repo "$STAGING_RELEASE_REPO_MLC"
+           cp staging/* ${CI_PACKAGE_REPO_STAGING}/ -rfa
+           rm -rf staging
+           gh release delete llm-staging-artifacts --cleanup-tag --yes --repo "$STAGING_RELEASE_REPO_MLC" || true
+           gh release create llm-staging-artifacts --latest --title llm-staging-artifacts --repo "$STAGING_RELEASE_REPO_MLC" --notes "Android (Adreno) LLM Nightly artifacts"
+           gh release upload llm-staging-artifacts $LLM_STAGING_ARTIFACTS/dist/libs/*.so --clobber --repo "$STAGING_RELEASE_REPO_MLC"
   BuildPackageWindows:
     needs: [BuildPackageLinux]
     if: ${{ github.repository == 'gpgpu/mlc-llm' }}
@@ -226,6 +387,12 @@ jobs:
         run: |
           git submodule sync --recursive
           git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          Push-Location
+          cd 3rdparty/tvm
+          git checkout -b rebase_staging origin/rebase_staging
+          git submodule sync --recursive
+          git -c protocol.version=2 submodule update --init --force --depth=0 --recursive
+          Pop-Location
       - name: Compile MLC
         shell: powershell
         run: |
@@ -270,7 +437,7 @@ jobs:
         run: |
            $env:PYTHONPATH = "$pwd\3rdparty\tvm\python;python"
            python -c "import mlc_llm; print(mlc_llm.__path__)"
-           ci/task/build_adreno_models_win_nightly.ps1 $Env:CI_LLM_NIGHTLY_ARTIFACTS
+           ci/task/build_adreno_models_win_nightly.ps1 $Env:CI_LLM_STAGING_ARTIFACTS
       - name: Build Package and Publish
         shell: powershell
         run: |
@@ -283,12 +450,12 @@ jobs:
            cd 3rdparty/tvm/python
            python.exe .\setup.py bdist_wheel --plat-name win_amd64
            Pop-Location
-           #try { gh release delete mlc-nightly --cleanup-tag --yes --repo $Env:RELEASE_REPO } catch { }
-           #gh release create mlc-nightly --latest --title mlc-nightly --repo $Env:RELEASE_REPO --notes "Windows MLC nightly builds"
-           gh release upload mlc-nightly .\build\mlc_llm-utils-win-x86.zip --clobber --repo $Env:RELEASE_REPO
-           foreach ($i in Get-ChildItem -Path python/dist) {gh release upload mlc-nightly .\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
-           foreach ($i in Get-ChildItem -Path 3rdparty/tvm/python/dist) {gh release upload mlc-nightly .\3rdparty\tvm\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
-           foreach ($i in Get-ChildItem -Path dist/libs/*.dll) {gh release upload llm-nightly-artifacts $i --clobber --repo $Env:RELEASE_REPO}
+           #try { gh release delete mlc-staging --cleanup-tag --yes --repo $Env:STAGING_RELEASE_REPO_MLC } catch { }
+           #gh release create mlc-staging --latest --title mlc-staging --repo $Env:STAGING_RELEASE_REPO_MLC --notes "Windows MLC staging builds"
+           gh release upload mlc-staging .\build\mlc_llm-utils-win-x86.zip --clobber --repo $Env:STAGING_RELEASE_REPO_MLC
+           foreach ($i in Get-ChildItem -Path python/dist) {gh release upload mlc-staging .\python\dist\$i --clobber --repo $Env:STAGING_RELEASE_REPO_MLC}
+           foreach ($i in Get-ChildItem -Path 3rdparty/tvm/python/dist) {gh release upload mlc-staging .\3rdparty\tvm\python\dist\$i --clobber --repo $Env:STAGING_RELEASE_REPO_MLC}
+           foreach ($i in Get-ChildItem -Path dist/libs/*.dll) {gh release upload llm-staging-artifacts $i --clobber --repo $Env:STAGING_RELEASE_REPO_MLC}
            # Copy to common Linux CI
            Copy-Item -Path .\build\mlc_llm-utils-win-x86.zip -Destination "$Env:CI_PACKAGE_REPO_NIGHTLY/"
            foreach ($i in Get-ChildItem -Path python/dist) {Copy-Item -Path .\python\dist\$i -Destination "$Env:CI_PACKAGE_REPO_NIGHTLY/"}
